pickUpPoint:
  x: 21
  y: 0
  z: 10
sortingPoints:
- name: blue
  points:
    x: 15
    y: 15
    z: 0
  categories:
  - blue
- name: test
  points:
    x: 203
    y: -10.8
    z: 0.5
  categories:
  - orange
  - blue
